# Copyright (C) 2024-2025 Mitsubishi Electric Research Laboratories (MERL)
#
# SPDX-License-Identifier: BSD-3-Clause

name: gram
channels:
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.2.2
  - torchvision=0.17.2
  - torchaudio=2.2.2
  - pytorch-cuda=11.8
  - tensorboard
  - matplotlib
  - numpy
  - pip
  - scipy
  - seaborn
  - moviepy
  - opencv
  - jupyter=1.0.0
  - glfw
  - gymnasium=0.29.1
  - pre-commit
  - black==22.12.0
  - flake8
  - pytest
